### ISSUE TITLE
user login

### ISSUE THREAD

**Issue by acdp10000** [lKinderBueno/Streamity-Xtream-IPTV-Web-player#2]
Hi i have notice account with user name with a - dont allow login is there any way to fix this issue?

**Comment by lKinderBueno** [comment]
Yes, I forgot to delete from a file a part from the Streamity main website file.
Go in "logDir/login/" and open the "Login.php" file.
Remove this part:
`if (!preg_match("/^[0-9a-zA-Z������������������������_]+$/", $user) && !preg_match("/^[a-zA-Z0-9\._-]+@[a-zA-Z0-9-]{2,}[.][a-zA-Z]{2,4}$/", $user))
    {
        $msg_login = "Username or password not valid";
        return;
    }

    if ((strpos($user, ' ') !== false) || strpos($user, '-') !== false || strpos($user, "'") !== false || strpos($user, '"') !== false)
    {
        $msg_login = "Username or password not valid";
        return;
    }
    if ((strpos($password, ' ') !== false) || strpos($password, "'") !== false || strpos($password, '"') !== false)
    {
        $msg_login = "Username or password not valid";
        return;
    }`

**Comment by acdp10000** [comment]
ok will do thanks for the reply
