### ISSUE TITLE
Error on Live Player

### ISSUE THREAD

**Issue by IanWONeill** [lKinderBueno/Streamity-Xtream-IPTV-Web-player#4]
Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/*****/streamity/player/live/index.php:2) in /usr/www/users/*****/streamity/player/live/m3uParserPlayer.php on line 38

Warning: count(): Parameter must be an array or an object that implements Countable in /usr/www/users/*****/streamity/player/live/index.php on line 28

**Comment by lKinderBueno** [comment]
It is a warning, not an error. In the install process  it is written "If you see "Warning and Notice" messages printed on your screen, disable "display_errors" or the player won't be visualized properly"
