### ISSUE TITLE
Someone please help me understand.

### ISSUE THREAD

**Issue by mhos** [lKinderBueno/Streamity-Xtream-IPTV-Web-player#41]
All,

I have setup a web server with apache php mariadb and have everything up and running.
All I am presented with is a login page.
But what is the login info?
Where do I get that?
Is that part of the IPTVEditor.com service or something?
The way this project looks to me is that I can install the player and load my on M3u files.
Is that not correct? I just don't understand the process here on how to actually use this.
I don't want an extra subscription to anything I just want to be able to load up my M3U links from a browser anywhere.
Is this not what this is for self-hosted?

Please any help advise on actually setting this up would be great. I cannot find any information anywhere.
All the steps are completed and yes I have looked at the CORS part but still not understanding how to create a user or if there is a default user.....

Thanks

**Comment by nienna6** [comment]
Este es un reproductor para servicios IPTV, no es un reproductor m3u, y debes ser el dueño para configurarlo para tus clientes

**Comment by mhos** [comment]
So you have to have a subscription with IPTVEditor.com? 
I have an IPTV Service I use and just want to be able to use this in a browser so I can watch TV anywhere.
Would have no clients besides myself. Is that not what this is? Still confused. Thought this was similar to a IPTV client App like TiViMate but just for self-hosted browser so I dont need an actual app.
Thank you for your help with me understanding.
Google Translate:
Entonces, ¿debe tener una suscripción con IPTVEditor.com?
Tengo un servicio de IPTV que uso y solo quiero poder usarlo en un navegador para poder ver televisión en cualquier lugar.
No tendría clientes además de mí. ¿No es eso lo que es esto? Sigo confundido. Pensé que esto era similar a una aplicación de cliente de IPTV como TiViMate, pero solo para un navegador autohospedado, por lo que no necesito una aplicación real.
Gracias por su ayuda con mi comprensión.

**Comment by nienna6** [comment]
No nesecitas estar suscrito a iptveditor funciona también con xtream UI, solo debes configurar tu host o DNS en config.js y ya debería estar configurado.
¿Que sistema usas para distribuir tu servicio IPTV?

**Comment by mhos** [comment]
I am using Eternal IPTV.
I have set the DNS in the config.js: XXXXX is the real link dns and port.
window.dns = "http://XXXXXXX.link:8080";

Error in the apache logs: Adjusted the details to protect
[Thu Mar 24 18:35:27.825731 2022] [proxy_fcgi:error] [pid 201] [client XXXXXXXXX:65087] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(http://XXXXXXXX.link:8080/player_api.php?username=XXXXXXXX&amp;password=XXXXXXX&amp;): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden\r\n in /var/www/html/proxy.php on line 16', referer: http://player.XXXXXXX.com/

Made sure there is no firewall on for testing either.
Any thoughts?
Tried window.cors = true; //false and window.cors = false; //false
Still continue to get Server didn't generated any reply. Please try later #2
Thanks

Google translate:
Estoy usando Eternal IPTV.
Configuré el DNS en config.js: XXXXX es el dns y el puerto del enlace real.
ventana.dns = "http://XXXXXXX.enlace:8080";

Error en los logs de apache: Ajustado los detalles para proteger
[Jue 24 de marzo 18:35:27.825731 2022] [proxy_fcgi:error] [pid 201] [cliente XXXXXXXXX:65087] AH01071: Obtuve el mensaje de error 'PHP: Advertencia de PHP: file_get_contents(http://XXXXXXXX.link:8080/player_api .php?username=XXXXXXXX&amp;password=XXXXXXX&amp;): no se pudo abrir la transmisión: ¡la solicitud HTTP falló! HTTP/1.1 403 Prohibido\r\n en /var/www/html/proxy.php en la línea 16', referente: http://player.XXXXXXX.com/

Se aseguró de que tampoco haya un firewall activado para realizar pruebas.
¿Alguna idea?
Intenté window.cors = true; //falso y ventana.cors = falso; //falso
Aún así, el servidor no generó ninguna respuesta. Inténtalo más tarde #2
Gracias

**Comment by nienna6** [comment]
La parte de CORS es solo para el main server donde está alojado el IPTV, el reproductor web no nesecita configurar la parte CORS, prueba con algún alojamiento  compartido o si gustas puedo ayudarte, escríbeme a WhatsApp o sms 
+1 (734) 724-7318

**Comment by mhos** [comment]
URL they have me use:
http://XXXXXXX.link:8080/get.php?username=XXXXXXX&password=XXXXXX&type=m3u_plus&output=ts

**Comment by mhos** [comment]
Just want to update, I did not understand the full aspect of this application and as an End user this is not for me. Thank you @nienna6 for your help in my understanding better.
