### ISSUE TITLE
Error on Series Player

### ISSUE THREAD

**Issue by IanWONeill** [lKinderBueno/Streamity-Xtream-IPTV-Web-player#6]
Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/*****/streamity/player/series/index.php:2) in /usr/www/users/*****/streamity/player/series/m3uParserPlayerSeries.php on line 31

Warning: count(): Parameter must be an array or an object that implements Countable in /usr/www/users/*****/streamity/player/series/index.php on line 18

**Comment by lKinderBueno** [comment]
It is a warning, not an error. In the install process  it is written "If you see "Warning and Notice" messages printed on your screen, disable "display_errors" or the player won't be visualized properly"
