### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by jfolhadeiuiu** [lKinderBueno/Streamity-Xtream-IPTV-Web-player#7]
Qual usuario e senha eu uso após instalar o script?

**Comment by lKinderBueno** [comment]
The one from you iptv provider

**Comment by jfolhadeiuiu** [comment]
Eu usei o Usuário e senha do provedor, porém não carrega permanece na tela
de login

Em ter, 21 de jul de 2020 04:46, lKinderBueno <notifications@github.com>
escreveu:
